### ISSUE TITLE
tmux prefix matching clashing

### ISSUE THREAD

**Issue by TomSteer1** [netkit-jh/netkit-jh-build#136]
**Describe the bug**
When attempting to start a lab with two machines using tmux, where the name of the second machine to start is a prefix of the first machine's name, Netkit produces an error stating that the session already exists.

**To Reproduce**
Steps to reproduce the behaviour:
1.  Create a lab with two machines, named `Machine` and `Machine-2.`
2.  Create a lab.dep file containing `Machine: Machine-2`. (Ensures the machines start in the order to produce the bug)
3.  Run the lab with tmux using the command lstart --tmux-attached.
 
**Expected behaviour**
Both machines should start normally, and each should launch a separate tmux window.

**Screenshots**
![image](https://user-images.githubusercontent.com/29020119/236297579-069ed31d-4317-4e7d-81f4-20e617ccf21c.png)

**Operating System**
- Host OS: Tested on Manjaro 22.1.0 ,6.2.13-arch1-1 and Ubuntu 20.04.4
- Guest OS: N/A

**Comment by AdamBromiley** [comment]
Hi Tom, thanks for raising this bug. The tmux command-line interface is a bit quirky and you ran into this issue:

https://github.com/tmux/tmux/issues/346
https://github.com/tmux/tmux/issues/1143

This issue also affected the functionality of `vcommand` and `vconnect`.

I've made a fix and will generate a new Netkit-JH release shortly 😄

**Comment by OwenHunter** [comment]
Adam my king 👑
