### ISSUE TITLE
`vclean --remove-tunnels` eval syntax error

### ISSUE THREAD

**Issue by AdamBromiley** [netkit-jh/netkit-jh-build#14]
**Describe the bug**
Running `vclean --remove-tunnels` results in an `eval` syntax error.

**To Reproduce**
1. Run `vclean --remove-tunnels` or `vclean --clean-all`

**Expected behavior**
Succesful removal of tap configurations

**Operating System**
Please include both the host and guest OS. If you are not using a VM, please enter N/A for guest OS.
- Host OS [e.g. Windows 10]: Windows 10
- Guest OS [e.g. Ubuntu 20.04]: Debian testing (bullseye/sid)

**Additional context**
```
debian@dysprosium:~$ vclean --remove-tunnels
************* Removing tap configurations ************
   This will affect tap configurations for user debian.
******** This operation requires root privileges ********
Running ==> /home/debian/netkit-jh/bin/manage_tuntap stop
/home/debian/netkit-jh/bin/vclean: 1: eval: Syntax error: Unterminated quoted string
```

**Comment by TechSupportJosh** [comment]
Fixed in 1689c7528eb208d3e8b380da4649f4e7cf3f62e2.
