### ISSUE TITLE
Replace references to the original Netkit dev team in `bugreport.man` and `netkit.7` manpages

### ISSUE THREAD

**Issue by AdamBromiley** [netkit-jh/netkit-jh-build#22]
`core/man/include/bugreport.man` and `core/man/man7/netkit.7` both instruct the contacting of the original Netkit/Netkit-NG authors for bugs or mailing.

While I don't recommend removing the list of original devlopers in `netkit.7` for their own legacy, it'd make sense to point all bug reports and development queries here.

**Comment by AdamBromiley** [comment]
*and also `core/README.mdown`

**Comment by AdamBromiley** [comment]
![image](https://user-images.githubusercontent.com/40538037/103490157-d8953600-4e11-11eb-80fa-f00e9d111edc.png)

**Comment by TechSupportJosh** [comment]
Updated in 49c2357ac8f8f5db53256ad919e1cfcc06ef10e6.

**Comment by netkit-jh** [comment]
Reopening on further discussion about removing most of the previous authors and instead including a thank you to the original developers to make it clear we are currently maintaining it.

**Comment by TechSupportJosh** [comment]
Updated in 6f7bbeebc3b13b460a700682e30727ca3f5f093e.
