### ISSUE TITLE
Handle configuration updates on reinstall/update

### ISSUE THREAD

**Issue by TechSupportJosh** [netkit-jh/netkit-jh-build#24]
**Is your feature request related to a problem? Please describe.**
When reinstalling or updating Netkit, the old netkit-jh directory is moved as a backup. However the configuration that you previously had is not copied over.

**Describe the solution you'd like**
When reinstalling or updating Netkit, your previous configuration should be copied into the new installation, and any new configuration options should be appended.

This may require including a version number into the Netkit config which will allow us to handle updates.

**Comment by netkit-jh** [comment]
Added in 9433887a49cd9d190a70f264edb47a9e6196794f.
