### ISSUE TITLE
Kernel Panic with gnome-terminal / tmux

### ISSUE THREAD

**Issue by b177y** [netkit-jh/netkit-jh-build#28]
**Describe the bug**

When starting a machine with networking capabilities (it has a tap interface or is on a collision domain) with gnome-terminal or tmux we get a kernel panic. 

**To Reproduce**
1. Install gnome-terminal, then open it and go to preferences. Under the command tab set 'when command exits' to 'hold the terminal open'. This will make it easier to see the machine output including the kernel panic.
2. Start a machine with `vstart a --eth0=tap,10.0.8.1,10.0.8.2 --xterm=gnome`

**Expected behavior**
The machine should boot up with a usable network interface.

**Screenshots**
Kernel panic trace:
https://paste.ubuntu.com/p/yHWSp5y9S8/

**Operating System**
Please include both the host and guest OS. If you are not using a VM, please enter N/A for guest OS.
- Host OS - arch linux
- Guest OS - none / ubuntu20.04 (tested both on arch host and in ubuntu vm, same trace)

**Additional context**
So far we think this is related to the networking vhubs, the daemon_open control connect fail appears to be trying to connect to the vhub .cnct unix socket.

**Comment by TechSupportJosh** [comment]
Gnome-terminal fix available in 5f16c1e819988f7b6bd758d3f1b3a3578fbcd5f6. #27 will need an update to work with this fix :-)
