### ISSUE TITLE
Consider piping startup files to /bin/bash instead of /bin/sh.

### ISSUE THREAD

**Issue by EdOverflow** [netkit-jh/netkit-jh-build#51]
Peter brought it to my attention that brace expansion does not work with `for` loops in startup files. In other words, the following code will just return the literal value `{1..8}`:

```bash
for i in {1..8}; do
    echo "$i"
done
```

It turns out you are piping startup files into `/bin/sh` which does not support brace expansion.

https://github.com/netkit-jh/netkit-jh-build/blob/0c9318c2c2bc969687a1104ec319e206137fb08e/fs/filesystem-tweaks/etc/netkit/netkit-phase2#L72

To fix this I suggest piping startup files into `/bin/bash` which would allow us to use brace expansion.

```bash
sed "s/\r$//" /hostlab/$HOSTNAME.startup | /bin/bash
```

I am more than happy to submit a pull request if necessary.

**Comment by TechSupportJosh** [comment]
Good catch, a PR would be much appreciated and we can get it into 1.1.2 👍
