### ISSUE TITLE
removeLabFolder() may result in rm -rf /

### ISSUE THREAD

**Issue by EdOverflow** [netkit-jh/netkit-jh-build#58]
The `removeLabFolder()` is asking for trouble due to the use of `rm -rf` which is then called in multiple locations where it could end up wiping random files on the user's host machine.

https://github.com/netkit-jh/netkit-jh-build/blob/209af1bb8be8b2660b9b35a6d0c77ce350b09c16/core/bin/lcommon#L124-L132

I would suggest using a safer approach.

**Comment by AdamBromiley** [comment]
Issue has been resolved in version 2.0.0-beta.
